### PR TITLE
Fix elementParentNode class list re-render issue

### LINKED ISSUE #201: Reapplying tether classes causes CSS animations to restart
I'll preface this by saying that it is not a good pattern for consumers of `react-tether` to create CSS selectors on library-controlled classes but it sometimes is necessary to apply "directional-specific" classes to bind "caret" css for tooltips and to use custom "expand/collapse" animations for the different positions.

Example:
```
.tether-element-attached-top .contents {
  animation-name: expand-down;
  animation-duration: 0.5s;
}
.tether-element-attached-bottom .contents {
  animation-name: expand-up;
  animation-duration: 0.5s;
}
```

It would be preferable if `react-tether` did not remove tether classes while doing an update so that CSS animations do not restart when the position of the tether has not changed. Currently, the code removes all tether-classes in `TetherComponent`, see latest code from #189 
```
var classStr = className || '';
if (this._elementParentNode.className !== classStr) {
    this._elementParentNode.className = classStr;
}
```
Then re-applies the same classes in `tether.position()` which causes **CSS animations to fire again.** This behavior was not present (perhaps overlooked) before when a `className` wasn't passed to the `TetherComponent` but I suspect this is done to compute the correct bounding boxes for tether positioning.

Old Code:
```
if (className) {
    this._elementParentNode.className = className;
}
```

Related CodePen (tether@1.0.2): https://codepen.io/j3tan/pen/exGRPw
Related CodePen (tether@2.0.2): https://codepen.io/j3tan/pen/JjPMxQx

Ideally, tether classes should only be removed/modified if they have changed during the update.

### PR DESCRIPTION
**Pull request by j3tan**
fixes #201

### CODE REVIEW

**Comment by j3tan** [comment]
Having quite a few issues trying to build/test/lint locally. A `CONTRIBUTING.md` doc would be helpful to external development :)

File: src/TetherComponent.jsx [hunk 1]
```diff
@@ -96,6 +96,15 @@ class TetherComponent extends Component {
       this._createContainer();
     }
 
+    // Verify if className props have changed
+    if (prevProps.className !== this.props.className) {
+      const prevClasses = (prevProps.className || '').split(' ');
```
Comment (j3tan) [inline src/TetherComponent.jsx]: This will need some tests but here's the general idea of what probably needs to happen to fix the re-render issue

File: src/TetherComponent.jsx [hunk 2]
```diff
@@ -96,6 +96,15 @@ class TetherComponent extends Component {
...
+      const currClasses = (this.props.className || '').split(' ');
+
+      this._elementParentNode.classList.remove(...prevClasses);
```
Comment (j3tan) [inline src/TetherComponent.jsx]: This step could probably be more optimized in only adding/removing classes that do not overlap. This is just simpler to read though.

File: src/TetherComponent.jsx [hunk 3]
```diff
@@ -96,6 +96,15 @@ class TetherComponent extends Component {
       this._createContainer();
     }
 
+    // Verify if className props have changed
+    if (this._elementParentNode && prevProps.className !== this.props.className) {
+      const prevClasses = (prevProps.className || '').split(' ');
```
Comment (j3tan) [inline src/TetherComponent.jsx]: Any suggestions on converting className strings to classList params are welcome

**Comment by j3tan** [comment]
@danreeves Hi Dan, could you take a look at this PR and test it out?

**Comment by danreeves** [comment]
This looks good to me
