### PR TITLE
Fix elementParentNode class list re-render issue in 1.x

### LINKED ISSUE #201: Reapplying tether classes causes CSS animations to restart
I'll preface this by saying that it is not a good pattern for consumers of `react-tether` to create CSS selectors on library-controlled classes but it sometimes is necessary to apply "directional-specific" classes to bind "caret" css for tooltips and to use custom "expand/collapse" animations for the different positions.

Example:
```
.tether-element-attached-top .contents {
  animation-name: expand-down;
  animation-duration: 0.5s;
}
.tether-element-attached-bottom .contents {
  animation-name: expand-up;
  animation-duration: 0.5s;
}
```

It would be preferable if `react-tether` did not remove tether classes while doing an update so that CSS animations do not restart when the position of the tether has not changed. Currently, the code removes all tether-classes in `TetherComponent`, see latest code from #189 
```
var classStr = className || '';
if (this._elementParentNode.className !== classStr) {
    this._elementParentNode.className = classStr;
}
```
Then re-applies the same classes in `tether.position()` which causes **CSS animations to fire again.** This behavior was not present (perhaps overlooked) before when a `className` wasn't passed to the `TetherComponent` but I suspect this is done to compute the correct bounding boxes for tether positioning.

Old Code:
```
if (className) {
    this._elementParentNode.className = className;
}
```

Related CodePen (tether@1.0.2): https://codepen.io/j3tan/pen/exGRPw
Related CodePen (tether@2.0.2): https://codepen.io/j3tan/pen/JjPMxQx

Ideally, tether classes should only be removed/modified if they have changed during the update.

### PR DESCRIPTION
**Pull request by j3tan**
Fixing re-render issue caused by a too-simplistic `className` check. The tether library adds its own classes to the tether parent node so it always mismatches the prop value

fixes #201

### CODE REVIEW

File: src/TetherComponent.jsx [hunk 1]
```diff
@@ -94,6 +94,20 @@ class TetherComponent extends Component {
     if (this._targetComponent && this._elementComponent) {
       this._createContainer();
     }
+
+    // Verify if className props have changed
+    if (this._elementParentNode && this.props.className !== props.className) {
```
Comment (j3tan) [inline src/TetherComponent.jsx]: Copied over from the other commit in (https://github.com/box/box-ui-elements/pull/1673)

This is in the `componentWillUpdate` to avoid refactoring `_update()` and closely mimics the other PR even though that one uses `componentDidUpdate`.

**Comment by j3tan** [comment]
strange, the component test passed before and still does locally

**Comment by danreeves** [comment]
Yeah, really strange. I'm not sure what's up

**Comment by j3tan** [comment]
I think something with the package lock caused the issue, may need to revert that completely

**Comment by j3tan** [comment]
oh i know, its the enzyme issue with react-test-renderer caused by the `UNSAFE_` change - the test suite uses `enzyme-adapter-react-install 15.5` which doesn't support it.

**Comment by j3tan** [comment]
Yep, short of forking the repo, we may want to publish these changes as a `1.1.0` and add some sort of documentation to README on `master` on resolving issues with React 15 and React 16.0-16.2 (i.e. using a fixed version of `react-tether` instead of a `^`.

thanks for taking the time to merge these changes though, will definitely help us clean up all those warnings we are getting

**Comment by danreeves** [comment]
@j3tan I think I'm happy with this last change. Thoughts? I really don't want to break compatibility

**Comment by j3tan** [comment]
Fix looks good to me. ship it!

File: src/TetherComponent.jsx [hunk 2]
```diff
@@ -286,4 +291,18 @@ class TetherComponent extends Component {
   }
 }
 
+function componentWillUpdate(nextProps) {
```
Comment (j3tan) [inline src/TetherComponent.jsx]: wish we could use `componentDidUpdate` but I don't think it's viable for React 15.x due to the way it'll render. We may want to test it, but I think this solution works for now

**Comment by mattcrowder** [comment]
Do you plan on publishing a minor version?

**Comment by danreeves** [comment]
Published in 1.0.5
